---
title: "Speeding up trace.DES"
author: "Alan Yang"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F, message=F)
```

# Results

```{r}
results <- data.frame(n_i = rep(c(10000, 50000, 100000, 150000, 200000, 300000, 500000), 2),
                      time = rep(0, 14),
                      Method = c(rep("trace.DES", 7), rep("trace.DES.new", 7))
)
results$time <- c(15.14, 141.66, 498.44, 852.65, 1358.38, 2666.03, 7446.84,
                  13.18,  92.53, 303.02, 550.78,  824.17, 1453.11, 4782.42) / 60
```

```{r}
options(scipen=999)
library(ggplot2)
ggplot(results, aes(x=n_i, y=time, group=Method)) +
  geom_line(aes(color=Method)) +
  geom_point(aes(color=Method)) +
  labs(title="trace.DES vs. trace.DES.new", 
       subtitle="A computational speed comparision",
       x="Number of individuals", y = "Time (in minutes)") +
  scale_x_continuous(breaks = c(10000, 50000, 100000, 150000,
                              200000, 300000, 500000),
                    labels = c("10,000", "50,000", "100,000", "150,000",
                              "200,000", "300,000", "500,000")) +
   scale_y_continuous(breaks = c(1, 10, 20, 30, 40, 50, 60, 70,  80, 90, 100, 110, 120)) +
  theme(axis.text = element_text(size = 7.3),
        panel.background = element_rect(fill = "white",
                                        colour = "black",
                                        size = 0.5, linetype = "solid"), 
        panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                        colour = "light grey"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                        colour = "light grey")) 
```

