---
active: true
date: "`r Sys.Date()`"
subtitle: ""
title: About this workshop
weight: 15
widget: custom
---

The Decision Analysis in R for Technologies in Health (DARTH) workgroup is offering a 4-day workshop from April 2nd - 5th 2024 in Toronto. This workshop gives you a unique opportunity to work together with experts in the field of decision modeling in R on a decision problem you bring yourself. 

As a participant you will bring your own decision problem and inputs, and decision modeling experts will guide you, step-by-step, through the decision model development process. We believe this one-on-one experience provides an excellent opportunity to learn about decision modelling in R while working on a real-world problem! This course will be tailored to individuals with a model at some stage of development, or a model developed in a different software (e.g. Excel, TreeAge) with the ambition to translate it to R. Familiarity with decision modelling, prior attendance of a DARTH decision modeling course and some experience with R software is expected.

Visit the [DARTH website](https://darthworkgroup.com/) for more information.




