---
active: true
date: "`r Sys.Date()`"
img: R_background.png
title: Next steps
weight: 1
---

### Workshop Preparation

Participants will be expected to have some experience with decision modeling and/or basic concepts of economic evaluation. A self-paced module introducing R concepts specifically for decision modeling will be provided as part of your workshop registration.

- August 23rd, 2024: Complete “Intro to R for Decision Modeling” modules on your own.

- August 22nd, 2024: Intro to R office hours (11:00am - 1:00pm Eastern Time)

### Workshop Schedule

- August 27: Decision trees and Markov models

- August 28: Microsimulation modeling

- August 29: Sensitivity analysis

### Workshop Details

- Asynchronous preparation (1-2 hours)

- Live interactive session (11:00am - 03:00pm Eastern Time in-person/zoom)

- Asynchronous completion of homework assignments (1-2 hours)

*Approximately 5 hours of lectures and assignments with approximately 4 hours of self-paced modules daily*

### Zoom Link

Will be posted soon.











