---
title: "Part I: Session 3"
date: "`r Sys.Date()`"
draft: false
type: docs
linktitle: "Session 3"
menu:
  day0:
    weight: 4
---

## Model Parameterization and Sensitivity Analysis

Wednesday, November 16, 2022

**Readings:**

- Briggs AH, Weinstein MC, Fenwick E, et al. Model parameter estimation and uncertainty analysis: a report of the ISPOR-SMDM modeling good research practices task force-6. Value in Health. 2012;15(5):835-842. [https://doi.org/10.1177/0272989x12458348](https://doi.org/10.1177/0272989x12458348)

- Lin JK, Lerman BJ, Barnes JI, Boursiquot BC, Tan YJ, Robinson AQ, Davis KL, Owens DK, Goldhaber-Fiebert JD. Cost effectiveness of chimeric antigen receptor T-cell therapy in relapsed or refractory pediatric B-cell acute lymphoblastic leukemia. Journal of Clinical Oncology. 2018;36(32):3192-202. [https://doi.org/10.1200/JCO.2018.79.0642](https://doi.org/10.1200/JCO.2018.79.0642)



**Schedule:**

|                            |            |
|---------------|:-----------------------------------------|
| 10:00am – 10:30am   | How do we parameterize models? |
| 10:30am – 11:00am  | Break out activity: discuss data needs of fellow modeling projects | 
| 11:00am – 12:00pm | Sensitivity analysis |
| 12:00pm – 12:30pm | R Shiny sensitivity analysis demonstration |


**Learning objectives:**

- Understand how decision analytic models are parameterized
-	Understand how to determine the data needs for a given modeling project
-	Understand the role of deterministic and probabilistic sensitivity analysis
-	Appropriately interpret the results from a sensitivity analysis

**Materials**

[Day 3 - Input parameters slides](../../../Course_Modularization/CDC 2022-23/Day 3 - Input_parameters_CDC.pdf)

[Day 3 - Sensitivity analysis slides](../../../Course_Modularization/CDC 2022-23/Day 3- Sensitivity Analysis - CDC 2022.pdf)

[Day 3 - Description of own case example template](../../../Course_Modularization/CDC 2022-23/Day 4 - Description of own case example_template.docx)

**Live session recording**

[Link](https://umn.zoom.us/rec/share/OCphTcyWbYbbeKVgkahFpE-x_Po_BHoGHdW0NKnjq0W7JHxa6fDNMWlypfmTHyrI.Fe_mj1o0yRF2xrM5)



