---
title: "Part I: Session 2"
date: "`r Sys.Date()`"
draft: false
type: docs
linktitle: "Session 2"
menu:
  day0:
    weight: 3
---

## Cohort State Transition Models

Tuesday, November 15, 2022

**Readings:**

- Coffin PO, Sullivan SD. Cost-effectiveness of distributing naloxone to heroin users for lay overdose reversal. Annals of Internal Medicine. 2013;158(1):1-9. [https://doi.org/10.7326/0003-4819-158-1-201301010-00003](https://doi.org/10.7326/0003-4819-158-1-201301010-00003)


**Schedule:**

|                            |            |
|---------------|:-----------------------------------------|
| 10:00am – 10:45am   | Cohort state-transition models |
| 10:45am – 11:30am  | Cohort state-transition model exercise: Managing residential toxin exposures | 
| 11:30am – 11:45am | Conceptualizing model structure |
| 11:45am – 12:15pm | Break out activity: discuss fellow modeling project ideas |
| 12:15pm – 12:30pm | Model structure Q&A  |


**Learning objectives:**

-	Understand the assumptions and mathematics behind cohort state-transition models
-	Understand how cohort state-transition models can be extended to reflect time-varying and time-dependent dynamics
-	Begin to understand when to use different types of models
-	Synthesize information into a state-transition model

