---
title: "Part I: Session 4"
date: "`r Sys.Date()`"
draft: false
type: docs
linktitle: "Session 4"
menu:
  day0:
    weight: 5
---

## Microsimulation Modeling

Thursday, November 17, 2022

**Readings:**

- Knudsen AB, Rutter CM, Peterse EF, Lietz AP, Seguin CL, Meester RG, Perdue LA, Lin JS, Siegel RL, Doria-Rose VP, Feuer EJ. Colorectal cancer screening: an updated modeling study for the US Preventive Services Task Force. JAMA. 2021;325(19):1998-2011. [https://doi.org/10.1001/jama.2021.5746](https://doi.org/10.1001/jama.2021.5746)



**Schedule:**

|                            |            |
|---------------|:-----------------------------------------|
| 10:00am – 11:00am   | [Microsimulation modeling](../../../Course_Modularization/CDC 2022-23/Day 4- Microsimulation - CDC 2022.pdf) |
| 11:00am – 11:15am | [Walk-through modeling project outline template (preparation for Part II)]((../../../Course_Modularization/CDC 2022-23/Day 4 - Description of own case example_template.docx)) | 
| 11:15am – 12:15pm | Break out activity: Complete an modeling project proposal |
| 12:15pm – 12:30pm | Wrap up |


**Learning objectives:**

-	Understand the structure of a microsimulation model
-	Deepen understanding of when to use different types of models
-	Understand the pros and cons of microsimulations versus cohort state-transition models
-	Outline a decision analytic model for a topic of interest

[Day 4 - Microsimulation slides](../../../Course_Modularization/CDC 2022-23/Day 4- Microsimulation - CDC 2022.pdf)

[Day 4 - Description of own case example template](../../../Course_Modularization/CDC 2022-23/Day 4 - Description of own case example_template.docx)

**Live session recording**

[Link](https://umn.zoom.us/rec/share/d_r8OqA1xpOf8X90uVLz6BpwXvSQ9GF7uluBcy6XHv1cRtlmV85y3rlp0h97e_Hv.ZX8R_Ar0pd7XlSRO)

