---
title: 'Cost-Effectiveness and Decision Modeling in R'
subtitle: 'Decision Tree Exercise - Ondansetron'
author: "The DARTH workgroup"
output:
  pdf_document: default
  html_document: default
---

Developed by the Decision Analysis in R for Technologies in Health (DARTH) workgroup:

Fernando Alarid-Escudero, PhD (1) 

Eva A. Enns, MS, PhD (2)	

M.G. Myriam Hunink, MD, PhD (3,4)

Hawre J. Jalal, MD, PhD (5) 

Eline M. Krijkamp, MSc (3)	

Petros Pechlivanoglou, PhD (6,7)

Alan Yang, MSc (7)

In collaboration of: 		

1. Drug Policy Program, Center for Research and Teaching in Economics (CIDE) - CONACyT, 
   Aguascalientes, Mexico
2. University of Minnesota School of Public Health, Minneapolis, MN, USA
3. Erasmus MC, Rotterdam, The Netherlands
4. Harvard T.H. Chan School of Public Health, Boston, USA
5. University of Pittsburgh Graduate School of Public Health, Pittsburgh, PA, USA
6. University of Toronto, Toronto ON, Canada
7. The Hospital for Sick Children, Toronto ON, Canada

Please cite our publications when using this code:
 
- Jalal H, Pechlivanoglou P, Krijkamp E, Alarid-Escudero F, Enns E, Hunink MG. 
An Overview of R in Health Decision Sciences. Med Decis Making. 2017; 37(3): 735-746. 
https://journals.sagepub.com/doi/abs/10.1177/0272989X16686559
 
- Krijkamp EM, Alarid-Escudero F, Enns EA, Jalal HJ, Hunink MGM, Pechlivanoglou P. 
Microsimulation modeling for health decision sciences using R: A tutorial. 
Med Decis Making. 2018;38(3):400–22. 
https://journals.sagepub.com/doi/abs/10.1177/0272989X18754513
 
- Krijkamp EM, Alarid-Escudero F, Enns E, Pechlivanoglou P, Hunink MM, Jalal H. 
A Multidimensional Array Representation of State-Transition Model Dynamics. 
Med Decis Making. 2020 Online first. https://doi.org/10.1177/0272989X19893973

Copyright 2017, THE HOSPITAL FOR SICK CHILDREN AND THE COLLABORATING INSTITUTIONS. 
All rights reserved in Canada, the United States and worldwide. Copyright, 
trademarks, trade names and any and all associated intellectual property are 
exclusively owned by THE HOSPITAL FOR Sick CHILDREN and the collaborating 
institutions. These materials may be used, reproduced, modified, distributed 
and adapted with proper attribution.

# Exercise I: Antiemetic prophylaxis during chemotherapy – A Decision Tree

You are tasked to evaluate the cost-effectiveness of ondansetron compared to metoclopramide for antiemetic prophylaxis in cancer patients undergoing chemotherapy (Buxton and O’Brien, 1992). Patients undergoing either of the two prophylactic treatments can experience significant emesis, as well as adverse drug effects (ADEs). Patients can receive treatment for the ADEs which is expected to affect the probability of an ADE being resolved. The two treatments differ with respect to the probability of emesis, and presence and resolution of ADEs. The economic outcome of interest is the total cost associated with a patient undergoing treatment on each strategy. The clinical outcome of interest is the probability of successful treatment, defined as absence of significant emesis or ADEs. The probabilities and costs associated with each event are presented in Table 1.

## Tasks

1. Sketch out the decision tree, with a particular focus on the outcome values (costs and probability of successful treatment) at terminal nodes.

2. The code template contains calculations for the “Ondansetron” strategy. Write code that calculates the expected outcomes for the “Metoclopramide” strategy.

3. Use the `calculate_icers(`) function from the ‘dampack’ package to calculate the incremental costs, Effectiveness, and ICERs of each strategy. Type “`?calculate_icers()`” to see function documentation.


**Table I: Input parameters**

|           **Parameter**             |  **R name**       |   **Value**       |
|:------------------------------------|:------------------|:-----------------:|
| Probabilities                       |                   |                   |  
| - Significant emesis, Ondansetron | `p_sem_on` | 0.25 |
| - Significant emesis, significant ADE, Ondansetron | `p_sem_ade_on` | 0.26 |
| - Significant emesis, significant ADE, treatment, Ondansetron| `p_sem_ade_trt_on` | 0.60 |
| - Significant emesis, significant ADE, treatment, resolution, Ondansetron |`p_sem_ade_trt_res_on` | 0.66 |
| - Significant emesis, significant ADE, no treatment, resolution, Ondansetron|`p_sem_ade_no_trt_res_on`| 1|
| - No significant emesis, significant ADE, Ondansetron | `p_no_sem_ade_on` | 0.11 |
| - No significant emesis, significant ADE, treatment, Ondansetron| `p_no_sem_ade_trt_on` | 0.17 |
| - No significant emesis, significant ADE, treatment, resolution, Ondansetron|`p_no_sem_ade_trt_res_on`| 1|
| - No significant emesis, significant ADE, no treatment, resolution, Ondansetron |`p_no_sem_ade_no_trt_res_on` | 1 |
| - Significant emesis, Metoclopramide | `p_sem_met` | 0.58 |
| - Significant emesis, significant ADE, Metoclopramide| `p_sem_ade_met` | 0.34 |
| - Significant emesis, significant ADE, treatment, Metoclopramide | `p_sem_ade_trt_met` | 0.60 |
| - Significant emesis, significant ADE, treatment, resolution, Metoclopramide |`p_sem_ade_trt_res_met`| 0.78|
| - Significant emesis, significant ADE, no treatment, resolution, Metoclopramide | `p_sem_ade_no_trt_res_met` | 1 |
| - No significant emesis, significant ADE, Metoclopramide|`p_no_sem_ade_met` | 0.12 |
| - No significant emesis, significant ADE, treatment, Metoclopramide |`p_no_sem_ade_trt_met` | 0.50 |
| - No significant emesis, significant ADE, treatment, resolution, Metoclopramide | `p_no_sem_ade_trt_res_met` | 1 |
| - No significant emesis, significant ADE, no treatment, resolution, Metoclopramide | `p_no_sem_ade_no_trt_res_met`| 1 |
| Total healthcare costs |  |  |
| - Treatment                     | `c_trt_met`     | $10 |
| - Episode of significant emesis | `c_sem_met`     | $30 |
| - ADE                           | `c_ade_met`     | $20 |
| - Treatment of ADE              | `c_ade_trt_met` | $5  |
