---
title: "Decision Modeling in R workshop"
author: "The DARTH workgroup"
subtitle: Decision Tree Exercise
output:
  html_document: default
  word_document: default
  pdf_document: default
---

Developed by the Decision Analysis in R for Technologies in Health (DARTH) workgroup:
Fernando Alarid-Escudero, PhD (1) 
Eva A. Enns, MS, PhD (2)	
M.G. Myriam Hunink, MD, PhD (3,4)
Hawre J. Jalal, MD, PhD (5) 
Eline Krijkamp, PhD (6)	
Petros Pechlivanoglou, PhD (7,8)
Alan Yang, MSc (8)

In collaboration of: 		

1. Stanford University, Stanford, CA, USA
2. University of Minnesota School of Public Health, Minneapolis, MN, USA
3. Erasmus MC, Rotterdam, The Netherlands
4. Harvard T.H. Chan School of Public Health, Boston, USA
5. University of Ottawa, Ottawa, ON, Canada
6. Erasmus University, Rotterdam, The Netherlands
7. University of Toronto, Toronto ON, Canada
8. The Hospital for Sick Children, Toronto ON, Canada


Please cite our publications when using this code:
 
- Jalal H, Pechlivanoglou P, Krijkamp E, Alarid-Escudero F, Enns E, Hunink MG. 
An Overview of R in Health Decision Sciences. Med Decis Making. 2017; 37(3): 735-746. 
https://journals.sagepub.com/doi/abs/10.1177/0272989X16686559

- Alarid-Escudero, F., Krijkamp, E.M., Pechlivanoglou, P. et al. A Need for Change! A Coding Framework for Improving Transparency in Decision Modeling. PharmacoEconomics 37, 1329–1339 (2019). https://doi.org/10.1007/s40273-019-00837-x


Copyright 2017, THE HOSPITAL FOR SICK CHILDREN AND THE COLLABORATING INSTITUTIONS. 
All rights reserved in Canada, the United States and worldwide. Copyright, 
trademarks, trade names and any and all associated intellectual property are 
exclusively owned by THE HOSPITAL FOR Sick CHILDREN and the collaborating 
institutions. These materials may be used, reproduced, modified, distributed 
and adapted with proper attribution.

# Exercise I: Treatment for Viral encephalitis – A Decision Tree

Viral encephalitis can be caused by herpes viruses (HVE) or other viruses (OVE). Herpes viruses cause approximately 52% of cases of viral encephalitis. Without treatment, the risk of complications (death or severe sequelae) for HVE is 71%; for OVE, the risk is only 1%. A drug, vidarabine, decreases the likelihood of complications due to HVE from 71% down to 36%. However, among OVE patients, treatment with vidarabine is associated with severe side effects, increasing the risk of complications from the 1% baseline to 20%. It is possible to obtain a definitive diagnosis of HVE by means of a brain biopsy, but the procedure itself also has a 0.5% probability of being fatal.

You are tasked with evaluating the healthcare costs and benefits associated with three possible management strategies (no treatment, vidarabine treatment, or brain biopsy followed by vidarabine treatment for those who are diagnosed with HVE). Benefits will be measured in terms of quality-adjusted life-years (QALYs). 

The healthcare cost of a case of viral encephalitis without complications is \$1,200; however, if complications occur, the cost rises to \$9,000. The cost of vidarabine treatment is \$9,500, while a brain biopsy is a \$25,000 procedure. 

A patient who recovers from viral encephalitis without complications has an average of 20 remaining QALYs; however, a patient who experiences complications has an average of 19 remaining QALYs. Since a brain biopsy is an unpleasant procedure, patients who undergo it also experience a one-time loss of 0.01 QALYs regardless of the outcome of the biopsy.

Parameters are summarized in Table 1. Use the code template provided in the “decision_tree_HVE_template.Rmd”   example as starting points for this exercise.

## Tasks

1. Access the HVE template decision tree using OpenTree (function open_tree() ).

2. The code template contains calculations for the "No Treatment" strategy. Use OpenTree and couple it with R code that calculates the expected outcomes for the two other strategies.

3. Use the `calculate_icers()` function from the `dampack` package to calculate the incremental costs, QALYs, ICERs and Incremantal NMB of each strategy, using a willingness to pay of $100,000/QALY. Type `?calculate_icers()` to see function documentation.

4. Plot the cost-effectiveness frontier using the "`plot()`" function and the output from the `calculate_icers()` function (see step 3 above)

**Table I: Input parameters**

|           **Parameter**             |  **R name**       |   **Value**       |
|:------------------------------------|:------------------|:-----------------:|
| Prevalence of HVE                   | `p_HVE`           | 0.52              |
| Probability of complications without treatment |   |    |
| - HVE                               | `p_HVE_comp`      | 0.71              |
| - OVE                               | `p_OVE_comp`      | 0.01              |
| Probability of complications with vidarabine treatment  |  |   |
| - HVE                               | `p_HVE_comp_tx`   |  0.36             |
| - OVE                               | `p_OVE_comp_tx`   |  0.20             |
| Probability of complications due to brain biopsy        | `p_biopsy_death`   | 0.005 |
| Quality-adjusted life-years (QALYs) |                   |                   |
| - Remaining QALYs without VE complications | `q_VE`     |  20               |
| - Remaining QALYs with VE complications | `q_VE_comp`   |  19               |
| - QALY loss due to brain biopsy     | `q_loss_biopsy`   |  0.01             |
| - QALY of death due to brain biopsy | `q_death_biopsy`  | $0                 |
| Healthcare costs                    |                   |                   |
| - Cost of viral encephalitis without complications | `c_VE`      | $1,200   |
| - Cost of viral encephalitis with complications    | `c_VE_comp` | $9,000   |
| - Vidarabine treatment              | `c_tx`            |  $9,500           |
| - Brain biopsy                      | `c_biopsy`        |  $25,000          |
| - Willingness-to-pay                | `wtp`             | $100,000/QALY     |
| - Cost of death due to brain biopsy | `c_death_biopsy`  | $0                |



