---
title: Set up GitHub
author: ''
date: "`r Sys.Date()`"
slug: github
categories: []
tags: []
linktitle: "GitHub"
menu:
  prework:
    parent: "Getting Started"
    weight: 3
toc: yes
type: docs
---

As experienced decision modelers, we strongly encourage using GitHub when using `R` for decision modeling. It offers multiple advantages:

- GitHub keeps a record of all previous versions of your code and files. If you make a mistake or accidentally delete your files, you can always retrieve them.

- You can easily share your model files with specific people, whether collaborators or your team. You can either choose to let them directly edit the files or only allow them to view and provide input. 

- You can easily share your model files with the general public for different purposes. For example, you can simply add the link to your project repository to your published papers.

We will use GitHub throughout this workshop to demonstrate its powerful functionality that can make decision modeling in `R` easier!.

**In order to get you started with using GitHub, we put together a [instruction sheet](../../../Course_Modularization/Intro, general, packages/Guide to Using GitHub.pdf). Please follow it closely.**

**If you have patient level data that you want to use for your decision model, please do not upload on Github. Instead, please reach out to alexandra.moskalewicz@sickkids.ca for further instructions.**
