---
title: "Cost-Effectiveness and Decision Modeling in R"
author: "The DARTH workgroup"
subtitle: Exercises – Survival analysis in Decision modeling   
output:
  html_document: default
  word_document: default
  pdf_document: default
---

Developed by the Decision Analysis in R for Technologies in Health (DARTH) workgroup:

Fernando Alarid-Escudero, PhD (1) 

Eva A. Enns, MS, PhD (2)	

M.G. Myriam Hunink, MD, PhD (3,4)

Hawre J. Jalal, MD, PhD (5) 

Eline M. Krijkamp, MSc (3)	

Petros Pechlivanoglou, PhD (6)

Alan Yang, MSc (7)

In collaboration of: 		

1. Drug Policy Program, Center for Research and Teaching in Economics (CIDE) - CONACyT, 
   Aguascalientes, Mexico
2. University of Minnesota School of Public Health, Minneapolis, MN, USA
3. Erasmus MC, Rotterdam, The Netherlands
4. Harvard T.H. Chan School of Public Health, Boston, USA
5. University of Pittsburgh Graduate School of Public Health, Pittsburgh, PA, USA
6. The Hospital for Sick Children, Toronto and University of Toronto, Toronto ON, Canada
7. The Hospital for Sick Children, Toronto ON, Canada

Please cite our publications when using this code:
 
- Jalal H, Pechlivanoglou P, Krijkamp E, Alarid-Escudero F, Enns E, Hunink MG. 
An Overview of R in Health Decision Sciences. Med Decis Making. 2017; 37(3): 735-746. 
https://journals.sagepub.com/doi/abs/10.1177/0272989X16686559
 
- Krijkamp EM, Alarid-Escudero F, Enns EA, Jalal HJ, Hunink MGM, Pechlivanoglou P. 
Microsimulation modeling for health decision sciences using R: A tutorial. 
Med Decis Making. 2018;38(3):400–22. 
https://journals.sagepub.com/doi/abs/10.1177/0272989X18754513
 
- Krijkamp EM, Alarid-Escudero F, Enns E, Pechlivanoglou P, Hunink MM, Jalal H. 
A Multidimensional Array Representation of State-Transition Model Dynamics. 
Med Decis Mak. 2020;40(2):242-248. https://doi.org/10.1177/0272989X19893973

Copyright 2017, THE HOSPITAL FOR SICK CHILDREN AND THE COLLABORATING INSTITUTIONS. 
All rights reserved in Canada, the United States and worldwide. Copyright, 
trademarks, trade names and any and all associated intellectual property are 
exclusively owned by THE HOSPITAL FOR SICK CHILDREN and the collaborating 
institutions. These materials may be used, reproduced, modified, distributed 
and adapted with proper attribution.

# Exercise: A 3-state Markov model

You were given access to individual-level data of patients with the hypothetical disease. Individuals are Sick (S1) and can transition to a Sicker state (S2) or die (D). From the data you are asked to inform the transition probabilities for the transitions from  S1 to S2 and from S1 to D directly from the data through the use of parametric survival functions. A snapshot of the data is presented below:

```{r}
data_long <- read.csv("data_long_Sicker.csv")
head(data_long)
```

## Tasks

1. Use the template `Markov_3_state_Survival_template.Rmd` as a starting point to code the survival analysis solution to the Sick-Sicker model.

2. Load the individual level data in long form from the `data_long_Sicker.csv` file.

3. Draw Kaplan Meier plots for each transition.

4. Estimate parametric distributions to the patient level survival data for both S1 -> D and S1 -> S2 transitions where assuming that the competing event is censored. HINT: you'll need to create two subsets, one for each transition.

5. Select the one with the most plausible fit (both clinically and statistically).

6. Extract transition probabilities for each transition. 

**OPTIONAL**

1. Incorporate the transition probabilities extracted from the survival analysis model to a Sick-Sicker time-dependent cohort state transition model.

2. Run the model and draw output from it.

**Table 1: Input parameters for the time-dependent Sick-Sicker cSTM **

|           **Parameter**            |  **R name** |   **Value**   |
|:-----------------------------------|:------------|:-------------:|
| Time horizon                       | `n_t`       | 30 years      |
| Cycle length                       |             | 1 year        |
| Names of health states             | `v_n`       | H, S1, S2, D  |
| Annual discount rate (costs/QALYs) | `d_r`       |  3%           |
| Annual transition probabilities    |             |               |
| - Sick individuals in S1           | `c_S1`      |  $4,000       |
| - Sick individuals in S2           | `c_S2`      |  $15,000      |
| - Dead individuals                 | `c_D`       |  $0           |
| - Additional costs of sick individuals treated in S1 or S2       | `c_trt` | $12,000 |
| Utility weights                    |             |               |
| - Healthy individuals              | `u_H`       |  1.00         |
| - Sick individuals in S1           | `u_S1`      |  0.75         |
| - Sick individuals in S2           | `u_S2`      |  0.50         |
| - Dead individuals                 | `u_D`       |  0.00         |
| Intervention effect                |             |               |
| - Utility for treated individuals in S1 | `u_trt` |  0.95        |
